# Generated by Django 3.1.1 on 2021-07-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0010_auto_20210727_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='webiste_url',
            new_name='website_url',
        ),
    ]
